'use strict';
/* Tests of the macros file of the formula preview (mathjax-macros.tex) as macros for KaTeX: parseKatexMacros (macrosPure.js) and
 * the file lookup (mathjaxFile.js, against a stub of vscode). The macros are checked with the real KaTeX of the extension.
 * Run from the repository root: node tests/mathjaxMacros.test.js [extension] */
const assert = require('assert');
const path = require('path');
const fs = require('fs');
const os = require('os');
const Module = require('module');
const EXT = path.resolve(__dirname, process.env.TSS_EXT || process.argv[2] || '../extension');
const MP = require(path.join(EXT, 'macrosPure.js'));
const katex = require(path.join(EXT, 'media', 'katex', 'katex.min.js'));
const { makeVscode } = require('./vscodeStub');

let n = 0;
const eq = (a, b, m) => { assert.deepStrictEqual(a, b, m); n++; };
const ok = (c, m) => { assert.ok(c, m); n++; };
const P = (t) => MP.parseKatexMacros(t);

// the forms of the file written by Generate MathJax macros file, and the ones written by hand
eq(P('\\newcommand{\\vect}[1]{\\mathbf{#1}}'), { '\\vect': '\\mathbf{#1}' });
eq(P('\\newcommand\\grad{\\nabla}'), { '\\grad': '\\nabla' }, 'no braces around the name');
eq(P('\\newcommand*{\\Re}[1]{\\operatorname{Re}(#1)}'), { '\\Re': '\\operatorname{Re}(#1)' }, 'starred');
eq(P('\\renewcommand{\\vec}[1]{\\boldsymbol{#1}}'), { '\\vec': '\\boldsymbol{#1}' }, 'renewcommand');
eq(P('\\DeclareMathOperator{\\rot}{rot}\n\\DeclareMathOperator*{\\argmin}{arg\\,min}'), { '\\rot': '\\operatorname{rot}', '\\argmin': '\\operatorname*{arg\\,min}' }, 'operators');
eq(P('\\def\\half#1{\\frac{#1}{2}}\n\\gdef\\two{2}'), { '\\half': '\\frac{#1}{2}', '\\two': '2' }, 'def');
eq(P('\\let\\eps\\varepsilon\n\\let\\ph=\\varphi'), { '\\eps': '\\varepsilon', '\\ph': '\\varphi' }, 'let');
eq(P('\\newcommand{\\pd}[2]{\\frac{\\partial #1}%\n{\\partial #2}}'), { '\\pd': '\\frac{\\partial #1} {\\partial #2}' }, 'a body over several lines, a comment inside');
eq(P('% \\newcommand{\\no}{x}\n\\newcommand{\\yes}{y} % \\newcommand{\\no2}{x}'), { '\\yes': 'y' }, 'comments are not read');
eq(P('\\newcommand{\\a}[1]{x}\n\\providecommand{\\a}[1]{WRONG}\n\\providecommand{\\b}{ok}'), { '\\a': 'x', '\\b': 'ok' }, 'providecommand does not replace');
eq(P('\\newcommand{\\a}{old}\n\\renewcommand{\\a}{new}'), { '\\a': 'new' }, 'the later definition wins');
// a default for the first argument is not expressible: left out, and an older definition of the name goes too
eq(P('\\newcommand{\\dd}[2][x]{\\mathrm{d}^{#2}}\n\\newcommand{\\ok}{1}'), { '\\ok': '1' }, 'default argument: left out');
eq(P('\\newcommand{\\dd}{old}\n\\renewcommand{\\dd}[2][x]{new}'), {}, 'and the older one is dropped');
eq(P('\\def\\x#1.{y}'), {}, 'a delimited \\def is left out');
eq(P(''), {}); eq(P(null), {}); eq(P('\\newcommand'), {}); eq(P('\\newcommand{\\a'), {}, 'broken input');

// the whole file of a real project goes through KaTeX
const file = [
  '% Generated by TSS Workflow from ConspectBook.cls',
  '% Skipped (not expressible in MathJax): foo',
  '\\newcommand{\\vect}[1]{\\boldsymbol{#1}}',
  '\\newcommand{\\grad}{\\nabla}',
  '\\newcommand{\\rot}{\\operatorname{rot}}',
  '\\DeclareMathOperator{\\Div}{div}',
  '\\newcommand{\\pd}[2]{\\frac{\\partial #1}{\\partial #2}}',
  '\\def\\half#1{\\frac{#1}{2}}'
].join('\n');
const macros = P(file);
const draw = (tex, m) => katex.renderToString(tex, { throwOnError: true, strict: 'ignore', macros: Object.assign({}, m) });
for (const tex of ['\\vect{j}', '\\grad \\vect{j}', '\\rot\\vect{B}', '\\Div \\vect{E}', '\\pd{f}{x}', '\\half{x}']) {
  ok(draw(tex, macros).includes('katex-html'), 'drawn: ' + tex);
  assert.throws(() => draw(tex, {}), /Undefined control sequence/, 'without the file ' + tex + ' is unknown');
  n++;
}

// the lookup of the file (mathjaxFile.js) with a stub of vscode
function lookup(dir, folders, cfgValues, act) {
  const h = makeVscode('x', [[0, 0, 0, 0]], {}, cfgValues || {});
  h.vs.workspace.workspaceFolders = folders.map((f) => ({ uri: { fsPath: f } }));
  const orig = Module._load;
  Module._load = function (req, ...rest) { return req === 'vscode' ? h.vs : orig.call(this, req, ...rest); };
  for (const key of Object.keys(require.cache)) if (key.startsWith(EXT) && /\.js$/.test(key)) delete require.cache[key];
  try { return act(require(path.join(EXT, 'mathjaxFile.js')), { uri: { fsPath: path.join(dir, 'a.tex') } }); } finally { Module._load = orig; }
}
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tss-mj-'));
try {
  lookup(tmp, [tmp], {}, (MJ, doc) => {
    eq(MJ.files(doc), [], 'no file: nothing');
    eq(MJ.macros(doc), {}); eq(MJ.stamp(doc), '');
  });
  const f = path.join(tmp, 'mathjax-macros.tex');
  fs.writeFileSync(f, '\\newcommand{\\grad}{\\nabla}\n');
  lookup(tmp, [tmp], {}, (MJ, doc) => {
    eq(MJ.files(doc), [f], 'the default name next to main.tex');
    eq(MJ.macros(doc), { '\\grad': '\\nabla' });
    const s1 = MJ.stamp(doc);
    ok(s1.includes(f), 'the stamp names the file');
    const later = new Date(Date.now() + 7000);
    fs.writeFileSync(f, '\\newcommand{\\grad}{g}\n'); fs.utimesSync(f, later, later);
    ok(MJ.stamp(doc) !== s1, 'the stamp changes when the file is saved');
  });
  // the name from tssworkflow.mathjaxMacrosFile, a sub folder, and an absolute path from latex-workshop; no duplicates
  fs.mkdirSync(path.join(tmp, 'tex'));
  fs.writeFileSync(path.join(tmp, 'tex', 'm.tex'), '\\newcommand{\\mine}{1}\n');
  lookup(tmp, [tmp], { mathjaxMacrosFile: 'tex/m.tex', 'hover.preview.newcommand.newcommandFile': f }, (MJ, doc) => {
    eq(MJ.files(doc), [path.join(tmp, 'tex', 'm.tex'), f], 'setting name first, then the file of LaTeX Workshop');
    eq(Object.keys(MJ.macros(doc)).sort(), ['\\grad', '\\mine']);
  });
  lookup(tmp, [tmp], { mathjaxMacrosFile: 'mathjax-macros.tex', 'hover.preview.newcommand.newcommandFile': 'mathjax-macros.tex' }, (MJ, doc) => eq(MJ.files(doc), [f], 'the same file twice is read once'));
  lookup(tmp, [], {}, (MJ, doc) => eq(MJ.files(doc), [], 'no workspace folder: nothing, no crash'));
} finally { fs.rmSync(tmp, { recursive: true, force: true }); }

console.log('mathjaxMacros: ' + n + ' checks passed');
